"""
Test and TestSubmission SQLAlchemy models.
"""

import enum
from datetime import datetime
from typing import Optional

from sqlalchemy import Boolean, DateTime, Enum, Float, ForeignKey, Integer, JSON, String, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base


class TestType(str, enum.Enum):
    online = "online"
    offline = "offline"


class Test(Base):
    """
    Represents a generated test.
    - source_file_url: MinIO URL of the uploaded PDF/image used for generation
    - questions: JSON array of question objects generated by the AI pipeline
    - expires_at: created_at + 3 days (the window during which students can attempt)
    """
    __tablename__ = "tests"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    title: Mapped[str] = mapped_column(String(300), nullable=False)
    teacher_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    grade: Mapped[int] = mapped_column(Integer, nullable=False, index=True)
    subject: Mapped[str] = mapped_column(String(100), nullable=False)
    source_file_url: Mapped[Optional[str]] = mapped_column(String(500), nullable=True)
    answer_key_url: Mapped[Optional[str]] = mapped_column(String(500), nullable=True)
    test_type: Mapped[TestType] = mapped_column(
        Enum(TestType, name='test_type'), nullable=False, default=TestType.online
    )
    # JSON structure: [{id, type, question, options?, answer, marks}, ...]
    questions: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)
    total_marks: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    time_limit_minutes: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    is_published: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    is_graded: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    # Students can only submit within this 3-day window
    expires_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)

    teacher = relationship("User", foreign_keys=[teacher_id])
    submissions = relationship("TestSubmission", back_populates="test", passive_deletes=True)

    def __repr__(self) -> str:
        return f"<Test id={self.id} title={self.title} grade={self.grade}>"


class TestSubmission(Base):
    """Records a student's attempt at an online test."""
    __tablename__ = "test_submissions"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    test_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("tests.id", ondelete="CASCADE"), nullable=False, index=True
    )
    student_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    # JSON: {question_id: answer_given, ...}
    answers: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)
    score: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    submitted_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    # True if the test timer expired and submission was triggered automatically
    auto_submitted: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)

    test = relationship("Test", back_populates="submissions")
    student = relationship("User", foreign_keys=[student_id])

    def __repr__(self) -> str:
        return f"<TestSubmission test_id={self.test_id} student_id={self.student_id} score={self.score}>"
